### ISSUE TITLE
not updating 

### ISSUE THREAD

**Issue by shimmmerman** [eq2reapp/eq2cmp-host#1]
I recently went to the site and its showing me at a 0 score and that was odd as a week ago it was in the upper 500s, I then looked and found that most of my stats show 0
see below

Heroic AAs | 0
Preorder Pet | 0
Flawless Buff | 0
Other | 0
Flawless Buff | 0

Just wanted to pass this on

**Comment by eq2reapp** [comment]
@shimmmerman Can you provide a character name to test? Sometimes if a character crashes while zoning, its stats can be messed up, but that should sort itself out the next time then login.

**Comment by shimmmerman** [comment]
You Bet
Composerzz on Skyfire

Thank you!!!!

**Comment by eq2reapp** [comment]
Thanks for the head's up, your character should be working properly now. You'll probably have to refresh your page to get the latest version of the site (or just use this link: https://eq2reapp.github.io/eq2cmp-host/?char=Skyfire.Composerzz).

Send me a tell in-game if you get a chance, thanks! `Skyfire.Reapp`
