### ISSUE TITLE
Suggestion: Add achievement "sets"

### ISSUE THREAD

**Issue by Lucutious** [eq2reapp/eq2cmp-host#2]
Currently, we can save groups of toons such that we can quickly flip through multiple sets and see perhaps different guilds, different friends, or whatever we wish to do.

It would be nice if we could do the same thing with the achievements on the report tab.

By the end of the year, I'll be tracking 18 different achievements for instanced avatars, 18 different achievements for contested avatars, flawless kills for 30+ raiders, and all of the kills in the Darkpaw instances (to help guide the group as to which names make the most sense to kill)

If I could save different groups of achievements to track, that would make it much cleaner.  Right now I pull a LOT of achievement ID's for each toon, and at any given time, 75% of them are unnecessary.

Maj_dul.Lucutious if you have any questions, or email me.

Thanks!

**Comment by eq2reapp** [comment]
@Lucutious I added a feature to save the achievements as groups, it's pretty basic but should be an improvement over what was there previously (nothing) 🙃
